### ISSUE TITLE
"Code Runner" addon fails to install

### ISSUE THREAD

**Issue by Raphiiko** [Digital-Alchemy-TS/addons#1]
**Bug description**

I've been looking to try out Digital Alchemy for Home Assistant, but I've been running into an issue, specifically with installing the "Code Runner" addon from this repository.

The issue is that I cannot get the addon to install. When attempting to do so, I run into the following error:

```
Failed to install add-on

 The command '/bin/ash -o pipefail -c npm i -g tsx nodemon' returned a non-zero code: 126 
 ```

![image](https://github.com/user-attachments/assets/b72c5069-f564-4e23-8565-63598e2fb005)

**How to reproduce**

1. I followed your ["Quickstart" documentation for HAOS](https://docs.digital-alchemy.app/docs/home-automation/quickstart/automation-quickstart/) first:
    1. I had Studio Code Server installed.
    2. I opened Studio Code Server within home assistant.
    3. I ran `curl -fsSL https://setup.digital-alchemy.app -o setup.sh; bash setup.sh` successfully within a terminal window, inside Studio Code Server.
    4. I configured `/config/home_automation/scripts/init.sh` as an `init_command` in the configuration of the Studio Code Server addon, and saved.
    5. I rebooted the Raspberry Pi running Home Assistant.
2. I added `https://github.com/Digital-Alchemy-TS/addons/` as a repository to home assistant.
3. I refreshed, and attempted to install the newly discovered "Code Runner" addon.

**Expected behaviour**

I would have expected the addon to succeed installing.

**Additional details**

I run the latest HAOS on a Raspberry Pi 4: HA Core 2024.7.4, HA Supervisor 2024.06.2, and HAOS 12.4.

If you need any additional information from me, feel free to let me know and I'll send it over. You can find me in your Discord as well if needed :) 

Thank you!

**Comment by QuadratClown** [comment]
Did you find a workaround for this issue? I have the same problem

Raspberry Pi 4 4Gb
Core 2024.8.2
Supervisor 2024.08.0
Operating System 13.1
Frontend 20240809.0

**Comment by zoe-codez** [comment]
Never got the notification from this 🫠 Checking into it 

- can replicate on a rpi4, looking into fixes

**Comment by zoe-codez** [comment]
Pushed `v24.8.1` and checked against my test pi. Error went away for me

> **Fix note**: The previous install method for nodejs was not valid for `arm` architectures. Fortunately the `apk add` now installs `node20` instead of 18, so DA compatibility is easy
